/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  docs: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['getting-started'],
    },
    {
      type: 'category',
      label: 'Versions',
      items: ['versions/version19', 'versions/version20', 'versions/version21'],
    },
    {
      type: 'category',
      label: 'Exports',
      items: ['exports/enumerations', 'exports/classes-entrypoint', 'exports/classes-groups', 'exports/interfaces'],
    },
  ],
}

module.exports = sidebars
