name: Publish Package to npmjs

on:
  push:
    branches: [master]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "library"
  cancel-in-progress: false

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.check.outputs.should_skip }}
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
      - id: check
        run: echo "should_skip=no" >> $GITHUB_OUTPUT
#        run: |
#          PUBLISHED_VERSION=$(npm show @zimo-elektronik/zcan version)
#          VERSION=$(npm pkg get version | tr -d '"')
#
#          if [ "$PUBLISHED_VERSION" = "$VERSION" ];
#          then
#            echo "Version didn't change, skipping"
#            echo "should_skip=yes" >> $GITHUB_OUTPUT
#          else
#            echo "should_skip=no" >> $GITHUB_OUTPUT
#          fi


  build:
    runs-on: ubuntu-latest
    needs:
      - check
    if:  ${{needs.check.outputs.should_skip == 'no'}}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
