name: Publish Package to npmjs

on:
  push:
    branches: [master]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "library"
  cancel-in-progress: false

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.step1.outputs.should_skip }}
    steps:
      - id: step1
        run: echo "should_skip=no" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs:
      - check
    if:  ${{needs.check.outputs.should_skip == 'no'}}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
