name: Publish Package to npmjs

on:
  push:
    branches: [master]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "library"
  cancel-in-progress: false

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          PUBLISHED_VERSION=$(npm show zcan version)
          VERSION=$(npm pkg get version | tr -d '"')

          if [ "$PUBLISHED_VERSION" = "$VERSION" ];
          then
            echo "Version didn't change, skipping"
            echo "::set-output name=should_skip::yes"
          else
            echo "::set-output name=should_skip::no"
          fi

  build:
    runs-on: ubuntu-latest
    needs:
      - version-check
    if: needs.version-check.outputs.should_skip == 'no'

    steps:
      - uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
